# python splitter.py -j jobs.txt -s 1 -tdp /mnt/qb/akata/shared/ffcv_imagenet100/train_500_0.50_90.ffcv -vdp /mnt/qb/akata/shared/ffcv_imagenet100/val_500_0.50_90.ffcv --scratch_data --num_gpus 4 --cpus 36 --mem 192
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mae.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=160 ++wandb.project="IN100_ffcv_ssl_aug_checks"

python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mae.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=160 ++wandb.project="IN100_ffcv_ssl_aug_checks"

python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++ffcv_augmentation="default_very_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++ffcv_augmentation="default_very_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++ffcv_augmentation="default_very_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++ffcv_augmentation="default_very_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++ffcv_augmentation="default_very_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++ffcv_augmentation="default_very_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++ffcv_augmentation="default_very_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++ffcv_augmentation="default_very_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mae.yaml ++ffcv_augmentation="default_very_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=160 ++wandb.project="IN100_ffcv_ssl_aug_checks"

python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mae.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=160 ++wandb.project="IN100_ffcv_ssl_aug_checks"

python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++ffcv_augmentation="minimal" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++ffcv_augmentation="minimal" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++ffcv_augmentation="minimal" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++ffcv_augmentation="minimal" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++ffcv_augmentation="minimal" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++ffcv_augmentation="minimal" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++ffcv_augmentation="minimal" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++ffcv_augmentation="minimal" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mae.yaml ++ffcv_augmentation="minimal" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=160 ++wandb.project="IN100_ffcv_ssl_aug_checks"




moco, default.
vicreg, swav not converging.
simsiam slowly converging.
simclr slowly converging.
barlow_twins slowly converging.
xent slowly converging.


# GROUP!!!

python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=400 ++wandb.project="IN100_ffcv_ssl_aug_checks" ++ffcv_dtype="float32"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=400 ++wandb.project="IN100_ffcv_ssl_aug_checks" ++ffcv_dtype="float32"





python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"



python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"

python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"

python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix"

python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++name="xent-imagenet100_float32" ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=400 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix" ++ffcv_dtype="float32"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++name="byol-imagenet100_float32" ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=400 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix" ++ffcv_dtype="float32"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++name="simclr-imagenet100_float32" ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=400 ++wandb.project="IN100_ffcv_ssl_aug_checks_fix" ++ffcv_dtype="float32"








# python splitter.py -j jobs2.txt -s 1 -tdp /mnt/qb/akata/shared/imagenet100/train -vdp /mnt/qb/akata/shared/imagenet100/val --scratch_data --num_gpus 4 --cpus 4 --mem 64 --dispatch --prepend bb --preemptable
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++name="xent_baseline" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=4 ++data.format="dali" ++strategy="ddp" ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=128 ++wandb.project="IN100_ssl_runs_dali"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++name="byol_baseline" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=4 ++data.format="dali" ++strategy="ddp" ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=128 ++wandb.project="IN100_ssl_runs_dali"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++name="barlow_baseline" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=4 ++data.format="dali" ++strategy="ddp" ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=128 ++wandb.project="IN100_ssl_runs_dali"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++name="simclr_baseline" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=4 ++data.format="dali" ++strategy="ddp" ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=128 ++wandb.project="IN100_ssl_runs_dali"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++name="vicreg_baseline" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=4 ++data.format="dali" ++strategy="ddp" ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=128 ++wandb.project="IN100_ssl_runs_dali"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++name="simsiam_baseline" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=4 ++data.format="dali" ++strategy="ddp" ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=128 ++wandb.project="IN100_ssl_runs_dali"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++name="mocov3_baseline" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=4 ++data.format="dali" ++strategy="ddp" ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=128 ++wandb.project="IN100_ssl_runs_dali"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++name="swav_baseline" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=4 ++data.format="dali" ++strategy="ddp" ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=128 ++wandb.project="IN100_ssl_runs_dali"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mae.yaml ++name="mae_baseline" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=4 ++data.format="dali" ++strategy="ddp" ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=40 ++wandb.project="IN100_ssl_runs_dali"
