
### Runs with W400
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++name="simclr-imagenet100-ffcv400" ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=256 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++name="vicreg-imagenet100-ffcv400" ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=256 ++wandb.project="IN100_ffcv_ssl_checks_V2"


### SwAV with Float 32, small and large BS
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++name="swav-imagenet100-bs200-float32" ++ffcv_augmentation="default" ++devices=[0,1] ++seed=0 ++data.num_workers=24 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=200 ++wandb.project="IN100_ffcv_ssl_checks_V2" ++ffcv_dtype="float32"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++name="swav-imagenet100-bs400-float32" ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=400 ++wandb.project="IN100_ffcv_ssl_checks_V2" ++ffcv_dtype="float32"

### Smaller BS
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++name="xent-imagenet100-bs256" ++ffcv_augmentation="default_weak" ++devices=[0,1] ++seed=0 ++data.num_workers=24 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=256 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++name="byol-imagenet100-bs256" ++ffcv_augmentation="default" ++devices=[0,1] ++seed=0 ++data.num_workers=24 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=256 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++name="barlow-imagenet100-bs256" ++ffcv_augmentation="default_weak" ++devices=[0,1] ++seed=0 ++data.num_workers=24 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=256 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++name="simclr-imagenet100-bs256" ++ffcv_augmentation="default" ++devices=[0,1] ++seed=0 ++data.num_workers=24 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=256 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++name="vicreg-imagenet100-bs256" ++ffcv_augmentation="vicreg" ++devices=[0,1] ++seed=0 ++data.num_workers=24 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=256 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++name="simsiam-imagenet100-bs256" ++ffcv_augmentation="default_weak" ++devices=[0,1] ++seed=0 ++data.num_workers=24 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=256 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++name="mocov3-imagenet100-bs256" ++ffcv_augmentation="default_weak" ++devices=[0,1] ++seed=0 ++data.num_workers=24 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=256 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++name="swav-imagenet100-bs256" ++ffcv_augmentation="default" ++devices=[0,1] ++seed=0 ++data.num_workers=24 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.batch_size=256 ++wandb.project="IN100_ffcv_ssl_checks_V2"

### Diff. Learning rates
# x0.3
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++name="xent-imagenet100-lrx03" ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.1 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++name="byol-imagenet100-lrx03" ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.17 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++name="barlow-imagenet100-lrx03" ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.1 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++name="simclr-imagenet100-lrx03" ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.1 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++name="vicreg-imagenet100-lrx03" ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.1 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++name="simsiam-imagenet100-lrx03" ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.17 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++name="mocov3-imagenet100-lrx03" ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.1 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++name="swav-imagenet100-lrx03" ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.17 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"

# # x0.1
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.03 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.06 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.03 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.03 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.03 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.06 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.03 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.06 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"

# x3
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++name="xent-imagenet100-lrx3" ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.9 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++name="byol-imagenet100-lrx3" ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=1.5 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++name="barlow-imagenet100-lrx3" ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.9 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++name="simclr-imagenet100-lrx3" ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.9 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++name="vicreg-imagenet100-lrx3" ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.9 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++name="simsiam-imagenet100-lrx3" ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=1.5 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++name="mocov3-imagenet100-lrx3" ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=0.9 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++name="swav-imagenet100-lrx3" ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=1.5 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"

# # x9
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name xent.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=2.7 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name byol.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=4.5 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name barlow.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=2.7 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simclr.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=2.7 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name vicreg.yaml ++ffcv_augmentation="vicreg" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=2.7 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name simsiam.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=4.5 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name mocov3.yaml ++ffcv_augmentation="default_weak" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=2.7 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"
# python main_pretrain.py --config-path scripts/replications/imagenet-100 --config-name swav.yaml ++ffcv_augmentation="default" ++devices=[0,1,2,3] ++seed=0 ++data.num_workers=36 ++data.format="ffcv" ++strategy="dp" ++precache=True ++data.train_path=$train_datapath ++data.val_path=$val_datapath ++optimizer.lr=4.5 ++optimizer.batch_size=512 ++wandb.project="IN100_ffcv_ssl_checks_V2"