defaults:
  - _self_
  - augmentations: supervised_symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "ContinualDistillation"
data:
  dataset: imagenet_subset
  n_data: 128117
  train_path: "/mnt/qb/akata/shared/ffcv_imagenet100/train_500_0.50_90.ffcv"
  val_path: "/mnt/qb/akata/shared/ffcv_imagenet100/val_500_0.50_90.ffcv"
  format: "ffcv"
  num_workers: 10
loss:
  name: 'xekl_mcl'
  alpha: 0.75
  kd_T: 0.1
  k: 30
  tau: 0.9999
  N: 2
optimizer:
  name: "SGD"
  batch_size: 128
  lr: 0.01
  weight_decay: 1e-4
  momentum: 0.9
scheduler:
  name: "None"
  warmup: 0
checkpoint:
  enabled: True
  dir: "trained_models/contdist"
  frequency: 1

on_flip:
  pos: 'distill'
  neg: 'nothing'
  neut: 'distill'

contdist:
  approach: 'simple'
  student_id: 123
  n_teachers: 5
  t_seed: 123

# overwrite PL stuff
max_epochs: 100
devices: [0, 1, 2, 3]
sync_batchnorm: True
accelerator: "gpu"
strategy: "dp"
precision: 16
seed: 123