defaults:
  - _self_
  - augmentations: supervised_symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "kl-distillation-imagenet"
data:
  dataset: imagenet
  train_path: "/mnt/qb/akata/shared/ffcv_imagenet100/train_500_0.50_90.ffcv"
  val_path: "/mnt/qb/akata/shared/ffcv_imagenet100/val_500_0.50_90.ffcv"
  format: "ffcv"
  num_workers: 36
freeze: False
loss:
  name: 'kl'
  alpha: None
optimizer:
  name: "SGD"
  batch_size: 128
  lr: 0.01
  classifier_lr: 0.1
  weight_decay: 1e-4
  momentum: 0.9
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
k: 10


# overwrite PL stuff
max_epochs: 100
devices: [0, 1, 2, 3]
sync_batchnorm: True
accelerator: "gpu"
strategy: "dp"
precision: 16
seed: 0