defaults:
  - _self_
  - augmentations: supervised_symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "cub"
data:
  dataset: CUB
  data_path: "/mnt/qb/akata/aoq877/"
  format: "ffcv"
  num_workers: 9
  num_classes: 200
  precision: 'half'
precache: True
ffcv_augmentation: 'default'
ffcv_dtype: 'float16'

loss:
  name: 'xe'

optimizer:
  name: "SGD"
  batch_size: 'auto'
  lr: 0.0001
  weight_decay: 1e-4
  momentum: 0.9

scheduler:
  name: CosineAnnealingLRwWarmup
  eta_min: 0.00002
  warmup: 5

checkpoint:
  enabled: True
  dir: "/mnt/qb/akata/aoq877/trained_models/trained_models"
  frequency: 1

search_id: None
model_id: 1

# overwrite PL stuff
max_epochs: 200
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "dp"
precision: 16
seed: 123