defaults:
  - _self_
  - augmentations: supervised_symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "xekl-distillation-imagenet"
data:
  dataset: imagenet_subset
  n_data: 128117
  train_path: "/mnt/qb/akata/shared/ffcv_imagenet100/train_500_0.50_90.ffcv"
  val_path: "/mnt/qb/akata/shared/ffcv_imagenet100/val_500_0.50_90.ffcv"
  format: "ffcv"
  num_workers: 36
loss:
  name: 'xekl'
  alpha: 0.5
  kd_T: 4
  k: 1000
  tau: 0.995
  N: 1
optimizer:
  name: "SGD"
  batch_size: 128
  lr: 0.01
  weight_decay: 1e-4
  momentum: 0.9
scheduler:
  name: "warmup_cosine"
  warmup: 0
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
search_id: None
student_id: 1
teacher_id: 2

on_flip:
  pos: 'distill'
  neg: 'nothing'
  neut: 'nothing'

# overwrite PL stuff
max_epochs: 100
devices: [0, 1, 2, 3]
sync_batchnorm: True
accelerator: "gpu"
strategy: "dp"
precision: 16
seed: 0