defaults:
  - _self_
  - pretrain@_global_

name: pretrain_caltech
ffcv_augmentation: default
seed: 1234
model_id: 41
max_epochs: 50
freeze: True
mode: Caltech_Finetune

data:
  dataset: caltech
  num_classes: 257
  num_workers: 10

optimizer:
  batch_size: auto
  lr: 0.1

wandb:
  project: Caltech_Pretrain

checkpoint:
  enabled: False

