defaults:
  - _self_
  - pretrain@_global_

name: pretrain_cub
ffcv_augmentation: default
seed: 1234
model_id: 41
max_epochs: 50
freeze: True
mode: CUB_Finetune

data:
  dataset: CUB
  num_classes: 200
  num_workers: 10

optimizer:
  batch_size: auto
  lr: 0.1

wandb:
  project: CUB_Pretrain

checkpoint:
  enabled: False
