defaults:
  - _self_
  - /augmentations/supervised_symmetric@_augmentations_
  - /wandb/private@_wandb_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "pretrain"
data:
  data_path: "path/to/data"
  format: "ffcv"
  precision: 'half'
precache: True
ffcv_augmentation: 'default'
ffcv_dtype: 'float16'

loss:
  name: 'xe'

optimizer:
  name: "SGD"
  batch_size: 'auto'
  lr: 0.0001
  weight_decay: 1e-4
  momentum: 0.9

scheduler:
  name: CosineAnnealingLRwWarmup
  eta_min: 0.00002
  warmup: 5

checkpoint:
  enabled: True
  dir: "path/to/checkpoints"
  frequency: 1

search_id: None
model_id: 1

# overwrite PL stuff
max_epochs: 200
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "dp"
precision: 16
seed: 123