defaults:
  - _self_
  - /augmentations/supervised_symmetric@_augmentations_
  - /wandb/private@_wandb_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "flips-study-imagenet"
data:
  dataset: imagenet100
  train_path: "/mnt/qb/akata/shared/ffcv_imagenet100/train_500_0.50_90.ffcv"
  val_path: "/mnt/qb/akata/shared/ffcv_imagenet100/val_500_0.50_90.ffcv"
  format: "ffcv"
  num_workers: 9
precache: True
ffcv_augmentation: True
ffcv_dtype: "float16"

optimizer:
  name: None
  batch_size: 128
  lr: 0
  weight_decay: None

loss:
  name: None

scheduler:
  name: None

checkpoint:
  enabled: False
  dir: None
  frequency: 0

topn: 1
p_values:
  - 2
  - 5
  - 20
  - 50

# overwrite PL stuff
max_epochs: 0
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "dp"
precision: 16
seed: 0