defaults:
  - _self_
  - augmentations: supervised_symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

# wandb project settings
wandb:
  enabled: True
  project: "repsssl_server_tests"

# base settings
name: "supervised_cls-imagenet2012"
method: "xent"
method_kwargs:
  temperature: 0.2
  proj_hidden_dim: 512
backbone:
  name: "resnet18"
data:
  dataset: imagenet
  train_path: "/mnt/qb/work/akata/kroth32/Datasets/ImageNet2012/train"
  val_path: "/mnt/qb/work/akata/kroth32/Datasets/ImageNet2012/val"
  format: "dali"
  num_workers: 8
optimizer:
  name: "lars"
  batch_size: 32
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
