defaults:
  - _self_
  - /augmentations/supervised_symmetric@_augmentations_
  - /wandb/private@_wandb_

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

data:
  dataset: imagenet_subset
  n_data: 128117
  train_path: "path/to/train.ffcv"
  val_path: "path/to/val.ffcv"
  format: "ffcv"
  num_workers: 9
precache: True
ffcv_augmentation: 'default'
ffcv_dtype: 'float16'

optimizer:
  name: "SGD"
  batch_size: 'auto'
  lr: 0.0001
  weight_decay: 1e-4
  momentum: 0.9

scheduler:
  name: None
  warmup: 0

checkpoint:
  enabled: True
  dir: "path/to/checkpoints"
  frequency: 1

on_flip:
  pos: 'distill'
  neg: 'distill'
  neut: 'distill'

# overwrite PL stuff
max_epochs: 20
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "dp"
precision: 16
seed: 123