defaults:
  - _self_
  - distillation@_global_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

name: "kl-pd-distillation-imagenet"

loss:
  name: 'xekl_dp'
  alpha: 1
  kd_T: 1
  k: 1000
  gamma: 1
  strat: 'most-conf'
  tau: None
  N: None
  label_smoothing: 0

search_id: None
student_id: 1
teacher_id: 2